---
dependencies: []

galaxy_info:
  role_name: auditbeat
  author: apolloclark
  description: Install and configure Elastic Auditbeat
  company: "Apollo Clark"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - monitoring
    - metrics
    - logging
    - security
    - devopssec
    - elastic
    - elk
    - auditbeat
