# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# apolloclark/auditbeat
auditbeat:
  version: "6.6.2"
  skip_restart: true
  modules:
    auditd:
      resolve_ids: true
      failure_mode: "silent"
      backlog_limit: 8196
      rate_limit: 0
      include_raw_message: true
      include_warnings: true
      socket_type: "multicast"
      audit_rule_files: []
      audit_rules:
        - w /etc/passwd -p wa -k identity
        - a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access
    file_integrity:
      paths:
        - /bin
        - /usr/bin
        - /sbin
        - /usr/sbin
        - /etc
  output:
    elasticsearch:
      enabled: true
      hosts:
        - "127.0.0.1:9200"
      username: elastic
      password: changeme