# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook_shared.yml

- hosts: all
  gather_facts: true
  become: true
  become_user: "root"
  vars_files:
    - vars.yml
  roles:
    - idealista.java_role
