# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: all
  connection: local
  gather_facts: no
  become: true
  become_user: "root"
  vars_files:
    - "vars.yml"
  roles:
    - apolloclark.metricbeat
