---
# https://docs.ansible.com/ansible/latest/modules/set_fact_module.html
- name: Get the simplified major.minor version string
  set_fact:
    version_simple: "{{ auditbeat.version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') }}"

# https://docs.ansible.com/ansible/latest/modules/include_vars_module.html
- name: Include defaults for configuration, per the requested version.
  include_vars:
    file: main-{{ version_simple }}.yml

# http://docs.ansible.com/ansible/latest/set_fact_module.html
- name: Merge auditbeat_default and auditbeat variables
  set_fact:
    auditbeat_combined: "{{ auditbeat_defaults | combine(auditbeat, recursive=True) }}"

# https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
# http://docs.ansible.com/ansible/latest/apt_key_module.html
- name: Add repository key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    id: "46095ACC8548582C1A2699A9D27D666CD88E42B4"
    state: present
  when:
    - auditbeat_combined.install_repo

# http://docs.ansible.com/ansible/latest/apt_repository_module.html
# https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
- name: Add Elastic 6.x repo (if choosing a 6.x version)
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    state: present
  when:
    - auditbeat_combined.version is version('6', '>=')
    - auditbeat_combined.version is version('7', '<')
    - auditbeat_combined.install_repo

# https://docs.ansible.com/ansible/latest/modules/apt_module.html
- name: Update apt cache
  apt: update_cache=yes
  when:
    - auditbeat_combined.install_repo

# https://docs.ansible.com/ansible/latest/modules/apt_module.html
- name: Install from repo (if choosing the 5.6.x or 6.x version)
  apt:
    name: "auditbeat={{ auditbeat_combined.version }}"
    state: present
  when:
    - auditbeat_combined.version is version('6', '>=')
    - auditbeat_combined.version is version('7', '<')
    - auditbeat_combined.install_repo

# https://docs.ansible.com/ansible/latest/modules/command_module.html
- name: Get the platform (i386 or amd64) of the virtual machine
  command: dpkg --print-architecture
  register: print_architecture

# https://docs.ansible.com/ansible/latest/modules/set_fact_module.html
- name: Set the actual platform value as a variable
  set_fact:
    platform: "{{ print_architecture.stdout }}"

# http://docs.ansible.com/ansible/latest/service_module.html
- name: Ensure auditbeat auto-starts
  service:
    name: auditbeat
    enabled: yes

# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file
  template:
    src: "auditbeat-{{ version_simple }}.yml"
    dest: "{{ auditbeat_combined.config_include_dir }}/auditbeat.yml"
    owner: root
    group: root
    mode: 0644
  when:
    - not auditbeat_combined.install_only

# https://docs.ansible.com/ansible/latest/modules/command_module.html
# https://www.elastic.co/guide/en/beats/auditbeat/6.2/configuration-template.html
- name: Configure the Elasticsearch index template
  command: auditbeat setup --template -E output.logstash.enabled=false -E output.kafka.enabled=false -E output.elasticsearch.enabled=true -E 'output.elasticsearch.hosts=["{{ item }}"]'
  loop: "{{ auditbeat_combined.output.elasticsearch.hosts }}"
  when:
    - auditbeat_combined.setup.template.enabled
    - auditbeat_combined.output.elasticsearch.hosts

# http://docs.ansible.com/ansible/latest/service_module.html
- name: Restart auditbeat
  service:
    name: "{{ auditbeat_combined.daemon }}"
    state: restarted
  when:
    - not auditbeat_combined.install_only

# http://docs.ansible.com/ansible/latest/service_module.html
- name: Ensure that the service is running
  service: 
    name: auditbeat
    state: started
    enabled: yes
  when:
    - not auditbeat_combined.install_only
